site: x3beche
title: x3beche
description: >-
  blog
googlewebfonts: Fira+Code:wght@400;500;700
lang: en-US
timezone: England
#repo: https://github.com/p0wex/Gesko -> source of this template
data-theme: dark # default theme "dark" | "light"

author:
  name: x3beche
  bio: just a minimalist, personal blog
  username: x3beche # general username
  github: x3beche # github username
  twitter: x3beche # twitter username
  email: x3beche@gmail.com # email adress

# URL settings
url: "https://x3beche.github.io" #
baseurl: "/" # leave blank if not wishd
permalink: "https://x3beche.github.io"
permalink: pretty


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
